# ~/.config/starship.toml

[prompt]
format = "$all"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"

[username]
show_always = true
style_user = "bold lavender"

[hostname]
ssh_only = true
style = "bold pink"

[directory]
truncation_length = 3
style = "bold blue"

[git_branch]
symbol = "ğŸŒ± "
style = "bold mauve"

[git_status]
style = "bold yellow"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ’€"
style = "bold green"

[time]
disabled = false
format = "ğŸ•’ %T"
style = "bold peach"

[cmd_duration]
min_time = 2000
format = "â± $duration"
style = "bold sky"

[package]
disabled = false
style = "bold rosewater"

