# ~/.config/starship.toml

# Prompt settings
add_newline = true
format = "$all"

# Customize prompt symbols
[character]
success_symbol = "[âžœ](bold green)"
error_symbol = "[âœ—](bold red)"

# Directory module
[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold blue"

# Git module
[git_branch]
symbol = "ðŸŒ± "
style = "bold purple"

[git_status]
style = "bold yellow
